name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 2 && echo "Lint passed"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 2 && echo "Tests passed"

  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 2 && echo "Build passed"
